var fs=require("fs");var f="D:/xiuxian/xiuxian/xiuxian-v2/src/lib/game/nodes.ts";var c=fs.readFileSync(f,"utf8");var NL="\n";var TAB="  ";
var L=[];
L.push(TAB+"// === Generate_NPC (codex) ===");
L.push(TAB+"if(name===\"Generate_NPC\"&&args.npcs){");
L.push(TAB+"for(var npc of args.npcs){newCodex.push({id:\"cv-\"+Date.now(),name:npc.name,entry_type:\"npc\",description:(npc.title?npc.title+\": \"+\"\"+npc.description+(npc.realm?\" [\"+npc.realm+\"]\"+\"\")+(npc.sect?\" \"+npc.sect:\"\")+(npc.personality?\" \"+npc.personality:\"\")+\"\",metadata:{},timestamp:Date.now()})}");
L.push(TAB+"}");
L.push(TAB+"// === Generate_Location (codex) ===");
L.push(TAB+"if(name===\"Generate_Location\"&&args.locations){");
L.push(TAB+"for(var loc of args.locations){newCodex.push({id:\"cv-\"+Date.now(),name:loc.name,entry_type:\"location\",description:loc.description+(loc.danger_level?\" [\"+loc.danger_level+\"]\"+\"\")+(loc.resources?\" \"+loc.resources:\"\")+(loc.creatures?\" \"+loc.creatures:\"\")+\"\",metadata:{},timestamp:Date.now()})}");
L.push(TAB+"}");
L.push(TAB+"// === Generate_Sect (codex) ===");
L.push(TAB+"if(name===\"Generate_Sect\"&&args.sects){");
L.push(TAB+"for(var sect of args.sects){newCodex.push({id:\"cv-\"+Date.now(),name:sect.name,entry_type:\"sect\",description:sect.description+(sect.alignment?\" [\"+sect.alignment+\"]\"+\"\")+(sect.master?\" \"+sect.master:\"\")+(sect.specialties?\" \"+sect.specialties:\"\")+\"\",metadata:{},timestamp:Date.now()})}");
L.push(TAB+"}");
L.push(TAB+"// === Generate_Item (codex) ===");
L.push(TAB+"if(name===\"Generate_Item\"&&args.items){");
L.push(TAB+"for(var item of args.items){newCodex.push({id:\"cv-\"+Date.now(),name:item.name,entry_type:\"item\",description:item.description+(item.grade?\" [\"+item.grade+\"]\"+\"\")+(item.effects?\" \"+item.effects:\"\")+\"\",metadata:{},timestamp:Date.now()})}");
L.push(TAB+"}");
var handler=L.join(NL)+NL;
c=c.replace("// === Write_Codex ===",handler+"// === Write_Codex ===");
fs.writeFileSync(f,c,"utf8");console.log("done",c.length);
